### ISSUE TITLE
Scoreboard issue

### ISSUE THREAD

**Issue by dotpeak** [Bexwing/docs#4]
### Server

Skyblock

### Steps to reproduce

1. Load into the game
2. Join Mob Arena (/ma join)
3. Wait for it to end or die

### Other information

The scoreboard on the side that shows balance and island stats goes away after returning to spawn from mob arena.

**Comment by BomBardyGamer** [comment]
I believe I know what causes this issue, and I will look in to a fix for this. Thanks for the report! :)

**Comment by BomBardyGamer** [comment]
Should be fixed on next restart
