### ISSUE TITLE
Cannot Claim Kits through Kit GUI

### ISSUE THREAD

**Issue by LyraFae-Lyra** [Bexwing/docs#5]
**Server:** Skyblock

**Steps Taken to Reproduce**

1. Type /kit
2. Click on money kit or donor kit in GUI
3. GUI closes and nothing happens

**Other Information**

I was able to claim the Bexwing kit through the command /kit bexwing. I could not figure out how to claim the money kits through a different command.

**IGN:** LyraFae

**Comment by dotpeak** [comment]
tru

**Comment by dylansoft** [comment]
This is no longer an issue as skyblock has since been removed.
